CHUNK_SIZE = 200
CHUNK_OVERLAP = 50

MAX_ENTITIES_PER_CHUNK = 8

MAX_CLAIMS_PER_CHUNK = 3
MIN_CLAIM_WORDS = 8
MAX_CLAIM_WORDS = 45

MAX_RECONCILIATION_CLAIMS = 12
MAX_RECONCILIATION_COMPARISONS = 30
CLAIM_RECONCILIATION_MAX_TOKENS = 180
