LLM_CONTEXT_CHUNKS = 5
LLM_MAX_NEW_TOKEN = 260
LLM_TEMPERATURE = 0
LLM_TIMEOUT_SECONDS = 180
OLLAMA_KEEP_ALIVE = "30m"
OLLAMA_PRELOAD_TOKENS = 1
CLAIM_EXTRACTION_MAX_TOKENS = 350
ENTITY_EXTRACTION_MAX_TOKENS = 250

MIN_ANSWER_DOCUMENTS = 2
MIN_AVERAGE_ANSWER_SCORE = 0.35
MIN_AVERAGE_SOURCE_RELIABILITY = 45
